### ISSUE TITLE
No output in rviz after running training script for PR2

### ISSUE THREAD

**Issue by MoreBrain** [robot-learning-freiburg/mobile-rl#1]
**What did you do?**
- followed steps from "Local installation" in Readme
- tried to run the training script and rviz:
"wandb offline"
"python src/modulation_rl/scripts/main_ray.py --load_bt_defaults --num_gpus 0.24 --num_workers 0 --num_cpus_per_worker 1 --num_envs_per_worker 1 --num_gpus_per_worker 0 --ray_verbosity 2 --training_intensity 0.1 --load_best_defaults --vis_env -d"
"rviz -d src/modulation_rl/rviz/rviz_config_pr2_real.rviz"

**What did you expect to happen?**
- gazebo starting up and see the robot training procedure
- seeing robot_model and sensor data in rviz

**What actually happened?**
terminal output:
Log path: /home/nsc/repos/n2m2_catkin_ws/src/modulation_rl/scripts/logs
/home/nsc/anaconda3/envs/modulation_rl/lib/python3.7/site-packages/ray/_private/services.py:238: UserWarning: Not all Ray Dashboard dependencies were found. To use the dashboard please install Ray using `pip install ray[default]`. To disable this message, set RAY_DISABLE_IMPORT_WARNING env var to '1'.
  warnings.warn(warning_message)
== Status ==
Memory usage on this node: 6.7/7.7 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/4 CPUs, 0/0 GPUs, 0.0/1.44 GiB heap, 0.0/0.72 GiB objects
Result logdir: /home/nsc/repos/n2m2_catkin_ws/src/modulation_rl/scripts/logs/ray/pr2_acceleration_penalty:0.05_dry_run:T_learn_torso:T_learn_vel_norm:0.1_training_intensity:0.1_transition_noise_base:0.04_mindispl1.0,0.0,1.0
Number of trials: 1/1 (1 PENDING)
== Status ==
Memory usage on this node: 6.6/7.7 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/4 CPUs, 0/0 GPUs, 0.0/1.44 GiB heap, 0.0/0.72 GiB objects
Result logdir: /home/nsc/repos/n2m2_catkin_ws/src/modulation_rl/scripts/logs/ray/pr2_acceleration_penalty:0.05_dry_run:T_learn_torso:T_learn_vel_norm:0.1_training_intensity:0.1_transition_noise_base:0.04_mindispl1.0,0.0,1.0
Number of trials: 1/1 (1 PENDING)
...

Probably I missed a certain procedure. Can you help me? :)

**Comment by dHonerkamp** [comment]
Hi, sounds like it is running.

Note that the training does not use gazebo, rather we train in an "analytical environment" which simply integrates the dynamics of the system over time. So there is no gazebo gui to start.

But you should be able to visualize it in rviz if you pass the --vis_env flag. By default it is set to the evaluation topics, but evaluation only happens every x steps, so most of the time there is nothing being published to these topics during training. To visualize the training rollouts, try changing the robot state and marker topics to train_env/... in rviz.

If that does not show anything either, try passing the --debug flag as well to run training in a local worker, I'm not sure off the top of my head if it will visualize it correctly while running in separate ray processes.

**Comment by dHonerkamp** [comment]
Closing this as there has been no further reply.
