### ISSUE TITLE
MPC launch file missing

### ISSUE THREAD

**Issue by JiahengHu** [robot-learning-freiburg/mobile-rl#2]
Seems that the launch file used for running the MPC baseline is missing. Is there any chance you can share the files necessary for running ocs2 baseline? Thanks!

**Comment by dHonerkamp** [comment]
Hi Jiaheng,

We do not include all the code for the baselines here, as we don't have the resources to clean and maintain versions of all the baselines. 

Nonetheless, you can find my fork of the ocs2 here: https://github.com/dHonerkamp/ocs2. Note that we have not tested the python scripts for the baselines that are included in this cleaned version of the repository and can also not fully say if this includes all components needed. So no guarantees that this will run out of the box or fully match the version used in the paper at this point.

But I hope it is still helpful to you.

**Comment by JiahengHu** [comment]
Thank you! That certainly helps!
